### ISSUE TITLE
error

### ISSUE THREAD

**Issue by deret00000** [oholiab/brute-seco#1]
hello mate! thank you for the soft. 
when im trying to execute it - i have got an error 

parallels@parallels-vm:~/Documents/brute$ node brute-seco.js seed.seco wordlist.txt
/home/parallels/Documents/brute/node_modules/seco-file/lib/index.js:12
  var _ref = _asyncToGenerator(function* (file, data, options = {}) {
                                                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/parallels/Documents/brute/brute-seco.js:1:76)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

please help me

**Comment by oholiab** [comment]
I have no idea why this is happening for you - can you clone the repo again and follow all the installation steps and post all the output? It looks like maybe the dependencies didn't install correctly, but that error is somewhere within one of the libraries and not in `brute-seco`'s code.

I can only give you so much help though because this was a CTF project from last year, and I'm really not a node expert.
